---
- name: Install NeatVideo OFX Plugin on AlmaLinux 9.6
  hosts: all
  become: yes
  
  vars:
    neatvideo_version: "5"
    neatvideo_installer: "NeatVideo5OFX.Studio.Intel64.run"
    neatvideo_source_path: "../../files/{{ neatvideo_installer }}"
    
    # Installation paths
    install_base: "/usr/local/Neat Video v5 OFX"
    ofx_plugin_path: "/usr/OFX/Plugins"
    
    # AD user settings
    ad_domain: "ad.noxvfx.com"
    ad_home_base: "/home/{{ ad_domain }}"
    skel_path: "/etc/skel"
    
    # License settings
    license_type: "studio"
    license_server: "5053@license"
    
    # Plugin configuration paths
    neatvideo_config_dir: ".neatvideo"
    neatvideo_temp_base: "/var/tmp/neatvideo"

  tasks:
    # ========================================
    # STEP 1: Copy and Install
    # ========================================
    - name: Copy NeatVideo installer to remote host
      copy:
        src: "{{ neatvideo_source_path }}"
        dest: /tmp/{{ neatvideo_installer }}
        mode: '0755'

    - name: Run NeatVideo installer in silent mode
      command: /tmp/{{ neatvideo_installer }} --mode silent
      args:
        creates: "{{ install_base }}"
      register: install_result

    - name: Show installation output
      debug:
        var: install_result.stdout_lines
      when: install_result.changed

    - name: Verify OFX plugin installation
      stat:
        path: "{{ ofx_plugin_path }}"
      register: ofx_check

    - name: Display installation status
      debug:
        msg: "NeatVideo OFX plugin installed at {{ ofx_plugin_path }}"
      when: ofx_check.stat.exists

    # ========================================
    # STEP 2: Remove Uninstall Desktop Shortcuts
    # ========================================
    - name: Remove uninstall text file from all AD user desktops
      shell: |
        find {{ ad_home_base }}/*/Desktop -name "Uninstall*.txt" -delete 2>/dev/null || true
      changed_when: false

    - name: Remove uninstall shortcuts from /etc/skel Desktop
      shell: |
        rm -f {{ skel_path }}/Desktop/Uninstall*.txt 2>/dev/null || true
      changed_when: false

    # ========================================
    # STEP 3: Configure License
    # ========================================
    - name: Configure NeatVideo floating license - system-wide
      lineinfile:
        path: /etc/environment
        regexp: '^NEATVIDEO_LICENSE='
        line: 'NEATVIDEO_LICENSE={{ license_server }}'
        create: yes
        mode: '0644'

    - name: Configure NeatVideo license for /etc/profile.d (all users)
      copy:
        content: |
          export NEATVIDEO_LICENSE={{ license_server }}
        dest: /etc/profile.d/neatvideo.sh
        mode: '0644'

    - name: Configure NeatVideo license in /etc/skel/.bashrc (new AD users)
      lineinfile:
        path: "{{ skel_path }}/.bashrc"
        regexp: '^export NEATVIDEO_LICENSE='
        line: 'export NEATVIDEO_LICENSE={{ license_server }}'
        create: yes
        mode: '0644'

    - name: Get list of existing AD users (UID > 400000000)
      shell: |
        getent passwd | awk -F: '$3 > 400000000 && $6 ~ /^\/home\/{{ ad_domain }}/ {print $1":"$6}'
      register: ad_users
      changed_when: false

    - name: Debug - Show detected AD users
      debug:
        msg: "Found {{ ad_users.stdout_lines | length }} AD users"
        verbosity: 1

    - name: Configure NeatVideo license for existing AD users
      lineinfile:
        path: "{{ item.split(':')[1] }}/.bashrc"
        regexp: '^export NEATVIDEO_LICENSE='
        line: 'export NEATVIDEO_LICENSE={{ license_server }}'
        create: yes
        mode: '0644'
        owner: "{{ item.split(':')[0] }}"
        group: "{{ item.split(':')[0] }}"
      loop: "{{ ad_users.stdout_lines }}"
      when: ad_users.stdout_lines | length > 0

    # ========================================
    # STEP 4: Configure Plugin Preferences
    # ========================================
    - name: Create NeatVideo config directory in /etc/skel
      file:
        path: "{{ skel_path }}/{{ neatvideo_config_dir }}"
        state: directory
        mode: '0755'

    - name: Create NeatVideo config directories for existing AD users
      file:
        path: "{{ item.split(':')[1] }}/{{ neatvideo_config_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ item.split(':')[0] }}"
        group: "{{ item.split(':')[0] }}"
      loop: "{{ ad_users.stdout_lines }}"
      when: ad_users.stdout_lines | length > 0

    # ========================================
    # STEP 5: Configure Temporary Files
    # ========================================
    - name: Create global NeatVideo temp directory
      file:
        path: "{{ neatvideo_temp_base }}"
        state: directory
        mode: '1777'

    - name: Create NeatVideo preferences file in /etc/skel
      copy:
        content: |
          # NeatVideo Preferences
          TempFolder={{ neatvideo_temp_base }}/$USER
        dest: "{{ skel_path }}/{{ neatvideo_config_dir }}/preferences.txt"
        mode: '0644'

    - name: Create user-specific temp directories for existing AD users
      file:
        path: "{{ neatvideo_temp_base }}/{{ item.split(':')[0] }}"
        state: directory
        mode: '0700'
        owner: "{{ item.split(':')[0] }}"
        group: "{{ item.split(':')[0] }}"
      loop: "{{ ad_users.stdout_lines }}"
      when: ad_users.stdout_lines | length > 0

    - name: Create NeatVideo preferences file for existing AD users
      copy:
        content: |
          # NeatVideo Preferences
          TempFolder={{ neatvideo_temp_base }}/{{ item.split(':')[0] }}
        dest: "{{ item.split(':')[1] }}/{{ neatvideo_config_dir }}/preferences.txt"
        mode: '0644'
        owner: "{{ item.split(':')[0] }}"
        group: "{{ item.split(':')[0] }}"
      loop: "{{ ad_users.stdout_lines }}"
      when: ad_users.stdout_lines | length > 0

    # ========================================
    # STEP 6: Cleanup
    # ========================================
    - name: Clean up installer file
      file:
        path: /tmp/{{ neatvideo_installer }}
        state: absent

    # ========================================
    # STEP 7: Verification
    # ========================================
    - name: Display installation summary
      debug:
        msg:
          - "========================================="
          - "NeatVideo Installation Complete"
          - "========================================="
          - "Plugin installed: {{ ofx_plugin_path }}"
          - "License server: {{ license_server }}"
          - "Config directory: ~/{{ neatvideo_config_dir }}"
          - "Temp directory: {{ neatvideo_temp_base }}/$USER"
          - "========================================="
          - "Usage in Nuke:"
          - "  Python: nuke.createNode('Reduce Noise v5')"
          - "  GUI: Tab menu → Filter → Neat Video → Reduce Noise v5"
          - "========================================="
          - "Host applications supported:"
          - "  - Nuke (commercial versions)"
          - "  - Fusion Studio"
          - "  - Flame"
          - "  - Baselight"
          - "  - And other OFX hosts"
          - "========================================="
