---
- name: Setup Local Cache Disk
  hosts: all
  become: yes

  vars:
    cache_mount_point: "/mnt/Cache"
    cache_label: "Cache"
    min_disk_size_bytes: 966367641600
    max_disk_size_bytes: 1181116006400

  tasks:
    - name: Ensure filesystem tools are installed
      ansible.builtin.dnf:
        name:
          - xfsprogs
          - e2fsprogs
        state: present

    - name: Gather storage facts
      ansible.builtin.setup:
        filter: ansible_devices

    - name: Find partition with the correct label
      ansible.builtin.set_fact:
        target_device_path: "/dev/{{ item }}"
      loop: >-
        {{
          [
            partition_name
            for device in ansible_devices.values()
            if device.partitions is defined
            for partition_name, partition_data in device.partitions.items()
            if partition_data.links is defined
            and partition_data.links.labels is defined
            and cache_label in partition_data.links.labels
          ]
        }}

    - name: Find an unformatted disk (if no labeled partition was found)
      block:
        - name: Find potential unformatted disks
          ansible.builtin.set_fact:
            potential_devices: >-
              {{
                ansible_devices | dict2items
                | selectattr('value.type', 'defined')
                | selectattr('value.type', 'equalto', 'disk')
                | selectattr('value.partitions', 'equalto', {})
                | selectattr('value.filesystem', 'undefined')
                | selectattr('value.size_bytes', '>=', min_disk_size_bytes)
                | selectattr('value.size_bytes', '<=', max_disk_size_bytes)
                | map(attribute='key')
                | list
              }}

        - name: Prompt to format if one potential disk is found
          ansible.builtin.pause:
            prompt: |
              Host: {{ inventory_hostname }}
              Found unformatted disk: /dev/{{ potential_devices[0] }}
              Do you want to format it as a cache drive? (yes/no)
          register: format_confirmation
          when: potential_devices | length == 1

        - name: Format the selected disk
          community.general.filesystem:
            fstype: xfs
            dev: "/dev/{{ potential_devices[0] }}"
            label: "{{ cache_label }}"
            force: yes
          when:
            - potential_devices | length == 1
            - format_confirmation.user_input | lower == 'yes'

        # This is the task that had the syntax error.
        # Ensure 'ansible.builtin.set_fact:' is all on one line.
        - name: Set the device path after formatting
          ansible.builtin.set_fact:
            target_device_path: "/dev/{{ potential_devices[0] }}"
          when:
            - potential_devices | length == 1
            - format_confirmation.user_input | lower == 'yes'
      when: target_device_path is not defined


    - name: Mount the cache drive if a device was found or created
      block:
        - name: Display final device path
          ansible.builtin.debug:
            msg: "Found or created cache device: {{ target_device_path }}"

        - name: Stop autofs to create mount point safely
          ansible.builtin.systemd:
            name: autofs
            state: stopped
          ignore_errors: yes

        - name: Create cache mount point
          ansible.builtin.file:
            path: "{{ cache_mount_point }}"
            state: directory
            mode: '0755'

        - name: Mount the cache disk and add to fstab
          ansible.builtin.mount:
            path: "{{ cache_mount_point }}"
            src: "LABEL={{ cache_label }}"
            fstype: xfs
            opts: defaults,noatime
            state: mounted

        - name: Set permissions for all users
          ansible.builtin.file:
            path: "{{ cache_mount_point }}"
            state: directory
            mode: '1777'
            owner: root
            group: root

        - name: Start autofs
          ansible.builtin.systemd:
            name: autofs
            state: started
          ignore_errors: yes

        - name: Display final summary
          ansible.builtin.debug:
            msg:
              - "Cache disk setup complete!"
              - "Device with Label '{{ cache_label }}' is mounted at {{ cache_mount_point }}."
      when: target_device_path is defined
