---
- name: Setup Local Cache Disk
  hosts: all
  become: yes

  vars:
    cache_mount_point: "/mnt/Cache"
    cache_label: "Cache"
    min_disk_size_bytes: 966367641600
    max_disk_size_bytes: 1181116006400

  tasks:
    - name: Ensure filesystem tools are installed
      ansible.builtin.dnf:
        name:
          - xfsprogs
          - e2fsprogs
        state: present

    - name: Gather storage facts
      ansible.builtin.setup:
        filter: ansible_devices

    - name: Find partition with the correct label
      ansible.builtin.set_fact:
        target_device_path: "/dev/{{ matching_partitions[0] }}"
      vars:
        matching_partitions: >-
          {%- set partitions = [] -%}
          {%- for device in ansible_devices.values() -%}
            {%- if device.partitions is defined -%}
              {%- for name, data in device.partitions.items() -%}
                {%- if data.links is defined and data.links.labels is defined and cache_label in data.links.labels -%}
                  {%- set _ = partitions.append(name) -%}
                {%- endif -%}
              {%- endfor -%}
            {%- endif -%}
          {%- endfor -%}
          {{- partitions -}}
      when: matching_partitions | length > 0

    - name: Find an unformatted disk (if no labeled partition was found)
      block:
        - name: Find potential unformatted disks
          ansible.builtin.set_fact:
            potential_devices: >-
              {%- set candidates = [] -%}
              {%- for name, data in ansible_devices.items() -%}
                {%- if data.partitions is defined and data.partitions == {}
                    and data.filesystem is undefined
                    and data.sectors is defined and data.sectorsize is defined
                    and (data.sectors | int * data.sectorsize | int) >= min_disk_size_bytes
                    and (data.sectors | int * data.sectorsize | int) <= max_disk_size_bytes -%}
                  {%- set _ = candidates.append(name) -%}
                {%- endif -%}
              {%- endfor -%}
              {{- candidates -}}

        - name: Prompt to format if one potential disk is found
          ansible.builtin.pause:
            prompt: |
              Host: {{ inventory_hostname }}
              Found unformatted disk: /dev/{{ potential_devices[0] }}
              Do you want to format it as a cache drive? (yes/no)
          register: format_confirmation
          when: potential_devices | length == 1

        - name: Format the selected disk
          ansible.builtin.filesystem: # Using core module
            fstype: xfs
            dev: "/dev/{{ potential_devices[0] }}"
            opts: "-L {{ cache_label }}" # FIX 1: Using 'opts' instead of 'label'
            force: yes
          when:
            - potential_devices | length == 1
            # FIX 2: Added 'format_confirmation is defined' for safety
            - format_confirmation is defined
            - format_confirmation.user_input | lower == 'yes'

        - name: Set the device path after formatting
          ansible.builtin.set_fact:
            target_device_path: "/dev/{{ potential_devices[0] }}"
          when:
            - potential_devices | length == 1
            # FIX 2: Added 'format_confirmation is defined' for safety
            - format_confirmation is defined
            - format_confirmation.user_input | lower == 'yes'
      when: target_device_path is not defined

    - name: Mount the cache drive if a device was found or created
      block:
        - name: Display final device path
          ansible.builtin.debug:
            msg: "Found or created cache device: {{ target_device_path }}"

        - name: Stop autofs to create mount point safely
          ansible.builtin.systemd:
            name: autofs
            state: stopped
          ignore_errors: yes

        - name: Create cache mount point
          ansible.builtin.file:
            path: "{{ cache_mount_point }}"
            state: directory
            mode: '0755'

        - name: Mount the cache disk and add to fstab
          ansible.builtin.mount:
            path: "{{ cache_mount_point }}"
            src: "LABEL={{ cache_label }}"
            fstype: xfs
            opts: defaults,noatime
            state: mounted

        - name: Set permissions for all users
          ansible.builtin.file:
            path: "{{ cache_mount_point }}"
            state: directory
            mode: '1777'
            owner: root
            group: root

        - name: Start autofs
          ansible.builtin.systemd:
            name: autofs
            state: started
          ignore_errors: yes

        - name: Display final summary
          ansible.builtin.debug:
            msg:
              - "Cache disk setup complete!"
              - "Device with Label '{{ cache_label }}' is mounted at {{ cache_mount_point }}."
      when: target_device_path is defined
