---
- name: Setup Local Cache Disk
  hosts: all
  become: yes

  vars:
    cache_mount_point: "/mnt/Cache"
    cache_label: "Cache"
    min_disk_size_bytes: 966367641600
    max_disk_size_bytes: 1181116006400

  tasks:
    - name: Ensure filesystem tools are installed
      ansible.builtin.dnf:
        name:
          - xfsprogs
          - e2fsprogs
        state: present

    - name: Gather storage facts
      ansible.builtin.setup:
        filter: ansible_devices

    #
    # === NEW DISCOVERY LOGIC STARTS HERE ===
    #
    - name: Find partition with the correct label
      ansible.builtin.set_fact:
        # The loop will contain the partition name, e.g., "nvme2n1p1"
        target_device_path: "/dev/{{ item }}"
      # This Jinja2 expression creates a list of partition names that have the 'Cache' label.
      # The Ansible 'loop' then iterates over that list.
      loop: >-
        {{
          [
            partition_name
            for device in ansible_devices.values()
            if device.partitions is defined
            for partition_name, partition_data in device.partitions.items()
            if partition_data.links is defined
            and partition_data.links.labels is defined
            and cache_label in partition_data.links.labels
          ]
        }}
    #
    # === NEW DISCOVERY LOGIC ENDS HERE ===
    #

    - name: Find an unformatted disk (if no labeled partition was found)
      block:
        - name: Find potential unformatted disks
          ansible.builtin.set_fact:
            potential_devices: >-
              {{
                ansible_devices | dict2items
                | selectattr('value.type', 'defined')
                | selectattr('value.type', 'equalto', 'disk')
                | selectattr('value.partitions', 'equalto', {})
                | selectattr('value.filesystem', 'undefined')
                | selectattr('value.size_bytes', '>=', min_disk_size_bytes)
                | selectattr('value.size_bytes', '<=', max_disk_size_bytes)
                | map(attribute='key')
                | list
              }}

        - name: Prompt to format if one potential disk is found
          ansible.builtin.pause:
            prompt: |
              Host: {{ inventory_hostname }}
              Found unformatted disk: /dev/{{ potential_devices[0] }}
              Do you want to format it as a cache drive? (yes/no)
          register: format_confirmation
          when: potential_devices | length == 1

        - name: Format the selected disk
          community.general.filesystem:
            fstype: xfs
            dev: "/dev/{{ potential_devices[0] }}"
            label: "{{ cache_label }}"
            force: yes
          when:
            - potential_devices | length == 1
            - format_confirmation.user_input | lower == 'yes'

        - name: Set the device path after formatting
          ansible
