---
- name: Dynamically Debug Storage Facts
  hosts: all
  gather_facts: no # We will gather them manually
  tasks:
    - name: Gather only storage facts
      ansible.builtin.setup:
        filter: ansible_devices

    - name: Find and display facts for the device containing the 'Cache' label
      ansible.builtin.debug:
        var: item.value # This prints all the facts for the device it found
      loop: "{{ ansible_devices | dict2items }}"
      when:
        - item.value.links is defined
        - item.value.links['by-label'] is defined
        - "'Cache' in item.value.links['by-label']"
